# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'HNKGooglePlacesAutocomplete-Example' do

pod 'HNKGooglePlacesAutocomplete', '~> 0.1'

end

target 'HNKGooglePlacesAutocomplete-ExampleTests' do

end

