# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'HNKGooglePlacesAutocomplete-Example' do

pod 'HNKGooglePlacesAutocomplete', :git => 'https://github.com/hkellaway/HNKGooglePlacesAutocomplete.git', :branch => 'core/model_setup_matched_substring'

end

target 'HNKGooglePlacesAutocomplete-ExampleTests' do

pod 'Kiwi', '~> 2.3'

end

