# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'HNKGooglePlacesAutocomplete-Example' do

pod 'HNKGooglePlacesAutocomplete', :git => 'https://github.com/hkellaway/HNKGooglePlacesAutocomplete.git', :branch => 'fix/query_config_offset'

end

target 'HNKGooglePlacesAutocomplete-ExampleTests' do

pod 'Kiwi', '~> 2.3'

end

